[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#777777"
blue = "#6f8fdb"
cyan = "#4ac9e2"
green = "#88db3f"
magenta = "#e987e9"
red = "#f36868"
white = "#FFFFFF"
yellow = "#f0bf7a"

[colors.cursor]
cursor = "#CECECE"
text = "#0E1415"

[colors.normal]
black = "#0E1415"
blue = "#4a88e4"
cyan = "#23acdd"
green = "#73ca50"
magenta = "#915caf"
red = "#e25d56"
white = "#f0f0f0"
yellow = "#e9bf57"

[colors.primary]
background = "#18181b"
foreground = "#CECECE"

[font]
size = 9

[font.bold]
family = "Monoid Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Monoid Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Monoid Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Monoid Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/bash"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"
