#! /bin/sh


# Bspwm Config

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Discord desktop='^4' 

# Keyboard Language
setxkbmap -option 'grp:alt_shift_toggle' -layout us,ge -variant qwerty

# Monitor Resolution
xrandr --output eDP1 --mode 1920x1080 &

# Startup Apps

exec $HOME/.config/bspwm/load.sh
